--EN
-- Not AutoGenerated
local debug = false --@debug@ debug = true --@end-debug@ 
local L = LibStub("AceLocale-3.0"):NewLocale("LFGStopWatch", "enUS", true,debug) 

--LFG_stopwatchcore
L["LFG StopWatch"] = true
L["Main Settings"] = true
L['StopWatch Start Delay'] = true
L['Set the start delay to shortest time possable for the most accurate time. Default is 15 secs.'] = true
L['Enable Lfg Stopwatch'] = true
L['If ON it will start the stopwatch when entering a lfg .If OFF it will not start the stopwatch. Default is ON'] = true
L["Enable the 'Time it took to complete this dungeon' Message"] = true
L["If checked it will enable the message.Default : enabled"] = true
L["Hide StopWatch Time Log Minimap Icon"] = true
L["If checked it will hide the MiniMap icon,if you want to see the Time Log use the /lfgswtime chat command"] = true
L["Time taken to complete this instance(When i joined): "] = true

--LFG_stopwatchtomelogframe
L["LFG StopWatch Time Log"] = true
--grouplist
L["Classic"] = true
L["The Burning Crusade"] = true
L["Wrath of the Lich King"] = true
L["Cataclysm"] = true
L["Mists of Pandaria"] = true
L["Warlords of Draenor"] = true
L["Legion"] = true
L["Battle for Azeroth"] = true
L["Shadowlands"] = true
--groupListRaids
L["TimeWalking"] = true
--TimeDunCols
L["Dungeon Name"] = true
L["Current Time"] = true
L["Old Time"] = true
L["Times Completed"] = true
--timeRaidCols
L["Raid Name"] = true
L["LFG StopWatch TimeLog"] = true
L["LFG StopWatch TimeLog"] = true
--Timelog tabs
L["Dungeons"] = true
L["Raids"] = true
L["Expansion: "] = true

