--itIT
-- LFGStopWatch AutoGenerated Localization if you want to help translate 
-- Go to https://www.curseforge.com/wow/addons/lfg-stopwatch/localization 

local L = LibStub("AceLocale-3.0"):NewLocale("LFGStopWatch", "itIT") 
if not L then return end
--@localization(locale="itIT", format="lua_additive_table",handle-unlocalized="english")@


